<?php
/**
 * Uninstall cleanup for BlogLogistics LLMs.txt Generator.
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
    exit;
}

delete_option( 'bloglogistics_llm_settings' );
delete_option( 'bloglogistics_llm_version' );
wp_clear_scheduled_hook( 'bloglogistics_llm_cron' );

global $wpdb;
$wpdb->delete( $wpdb->postmeta, [ 'meta_key' => '_ble_exclude_llm' ], [ '%s' ] );

$llms_path = untrailingslashit( ABSPATH ) . '/llms.txt';
if ( is_file( $llms_path ) && is_readable( $llms_path ) ) {
    $content = file_get_contents( $llms_path );
    if ( is_string( $content ) && false !== strpos( $content, 'Generated by BlogLogistics LLMs.txt Generator' ) && is_writable( $llms_path ) ) {
        unlink( $llms_path );
    }
}
